//
//  AppIntents.swift
//  GENERATED by preview-swiftui. Edit freely; it will not be rewritten.
//
//  A stand-in for `AppIntents`, which this engine cannot compile. Without
//  it AppIntentService.swift is dropped from the build, and so is everything that
//  needs what AppIntentService.swift declares.
//
//  WHAT IS REAL: the shape. Enough declarations for the files that
//  import `AppIntents` to compile and for their types to exist again.
//
//  WHAT IS NOT: the behaviour. Every function here returns an empty or
//  zero value. A screen rendering something this module would have
//  produced will come up EMPTY rather than wrong, and that is a
//  stand-in doing its job, not a layout bug.
//
//  TO MAKE A SCREEN LOOK REAL, put sample data here: give a function a
//  believable return value rather than an empty one. This file is
//  yours now; the engine will not touch it again. Delete it to have a
//  fresh draft written.
//

import Foundation
// SwiftUI too, because a stand-in for a UI library is asked to be a
// View: the app chains modifiers onto it, or returns it from a
// `some View` body. Without this the repair that adds the conformance
// cannot compile, and neither can anything a person adds by hand.
import SwiftUI

// NOT DECLARED HERE, on purpose: Bool, Equatable, Observable, Sendable, String
//
// Each of those names already exists, in the toolchain or in this
// engine. Declaring one here would shadow the real one in every
// file that imports both, and the build would fail somewhere with
// no visible connection to this file.
//
// If `AppIntents` genuinely exports one of them, the compiler will
// ask for it by name. Add it below and give it a distinct name, or
// accept that the call site has to qualify it.
/// Stand-in for `AppIntents.AppIntent`.
///
/// A class rather than a struct so it can be subclassed and passed
/// where a reference is expected, and open so an adapter can
/// specialise it. Members get added as the compiler asks for them.
/// `@unchecked Sendable` because a stand-in holds no state at all,
/// so there is nothing to race over. Without it, any app that
/// awaits a method on one fails with "sending 'x' risks causing
/// data races", which is true of the real type and never of this.
open class AppIntent: @unchecked Sendable {
    nonisolated public init() {}
}

