//
//  UIKit.swift
//  GENERATED by preview-swiftui. Edit freely; it will not be rewritten.
//  Generated from MobAI normalized Apple SDK IR.
// mobai-uikit-base: 1
//
//  This exists so `import UIKit` resolves. The UIKit types themselves
//  ship with the engine and are already visible in every file, so
//  there is deliberately nothing here to duplicate them: a second
//  UIScreen or UIColor gives the compiler two of each and produces
//  errors that name neither. A UIKit name the engine does NOT carry
//  is appended below from the SDK IR when a file asks for it, and
//  the engine keeps appending on later runs; what you write here
//  stays.
//
//  HapticManager.swift is what asked for UIKit here.
//
//  WHAT IS REAL: the shape, and state that reads back what was written.
//  A `UIViewRepresentable` runs its `makeUIView` and `updateUIView`, so
//  the app's own setup executes; a view holding text draws that text.
//
//  WHAT IS NOT: anything reaching a system. Feedback generators do
//  nothing. `UIApplication.shared.open` returns false. `UIScreen` and
//  `UIDevice` report a plausible phone, not this machine.
//
//  TO ADD WHAT YOUR APP NEEDS, put it here: an extension on a shipped
//  type, or a type the engine does not carry. To change a shipped one,
//  subclass it - they are open. This file is yours; the engine will not
//  touch it again.
//

// Re-exported, because that is what UIKit does on a phone: a file that
// says `import UIKit` and nothing else still sees CGFloat, CGRect and
// NSObject. Plain imports here left those invisible, and the compiler
// said "cannot find type 'CGFloat' in scope; did you mean to use
// 'CGFloat'?", which is what it says when a type exists but arrived
// through an import that does not carry it onward.
@_exported import Foundation
@_exported import MobAIPreviewFoundation
// `import UIKit` brings CoreGraphics on a phone: a model file that
// imports UIKit and returns a CGImage is ordinary. `canImport`, not
// `os(Linux)`: this file is staged through the iOS placement, which
// rewrites os() checks, and on Linux the name resolves through the
// engine's aliased shim.
#if canImport(CoreGraphics)
  @_exported import CoreGraphics
#endif

// ImageIO rides along too, because that is what UIKit does on a
// phone: CGImageSourceCreateWithURL in a file that imports UIKit
// alone is normal app code. On this machine the real framework
// decodes for real; on Linux the guard leaves this out.
#if canImport(ImageIO)
  @_exported import ImageIO
#endif

// Observation rides along as well: a phone's UIKit reaches it through
// Foundation, and files like a SceneDelegate use @Observable with only
// `import UIKit` at the top. The SwiftUI shim exports the same module,
// so a file importing both sees one Observation, not two.
@_exported import Observation
#if canImport(AppKit)
// The REAL attachment type: Foundation's attributed-string APIs on
// this host take AppKit's, and a twin was unconvertible to it.
import AppKit
public typealias NSTextAttachment = AppKit.NSTextAttachment
#else
// Linux has no AppKit and Foundation's attributed strings there take
// no attachment type at all; a bare twin keeps the name compiling.
open class NSTextAttachment: NSObject {
    open var image: UIImage?
    open var bounds: CGRect = .zero
    public override init() { super.init() }
    public init(image: UIImage) { self.image = image; super.init() }
}
#endif

// mobai-ir-declaration: UIActivity
public class UIActivity {
    public var activityViewController: UIViewController? { nil }

    public init() {}

    public struct ActivityType: Hashable {
        public init(_ value0: String) {}
    
        public init(rawValue value0: String) {}
    
        public var rawValue: String { "" }
    
        public typealias RawValue = String
    
        public typealias _ObjectiveCType = NSString
    
        public static var postToFacebook: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var postToTwitter: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var postToWeibo: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var message: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var mail: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var print: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var copyToPasteboard: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var assignToContact: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var saveToCameraRoll: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var addToReadingList: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var postToFlickr: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var postToVimeo: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var postToTencentWeibo: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var airDrop: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var openInIBooks: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var markupAsPDF: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var sharePlay: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var collaborationInviteWithLink: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var collaborationCopyLink: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    
        public static var addToHomeScreen: UIActivity.ActivityType { fatalError("preview SDK mock has no inert value for UIActivity.ActivityType") }
    }
}

extension UIActivity: Swift.Equatable, Swift.Hashable {
    public static func == (l: UIActivity, r: UIActivity) -> Bool { l === r }
    public func hash(into hasher: inout Swift.Hasher) {
        hasher.combine(Swift.ObjectIdentifier(self))
    }
}

// mobai-ir-declaration: UIActivityItemSource
public protocol UIActivityItemSource {
    func activityViewControllerPlaceholderItem(_ value0: UIActivityViewController) -> Any

    func activityViewController(_ value0: UIActivityViewController, itemForActivityType value1: UIActivity.ActivityType?) -> Any?

    func activityViewController(_ value0: UIActivityViewController, subjectForActivityType value1: UIActivity.ActivityType?) -> String

    func activityViewController(_ value0: UIActivityViewController, dataTypeIdentifierForActivityType value1: UIActivity.ActivityType?) -> String

    func activityViewController(_ value0: UIActivityViewController, thumbnailImageForActivityType value1: UIActivity.ActivityType?, suggestedSize value2: CGSize) -> UIImage?
}

private final class _MobAIUIActivityItemSource: UIActivityItemSource {
    init() {}

    @discardableResult
    public func activityViewControllerPlaceholderItem(_ value0: UIActivityViewController) -> Any { fatalError("preview SDK mock has no inert value for Any") }

    @discardableResult
    public func activityViewController(_ value0: UIActivityViewController, itemForActivityType value1: UIActivity.ActivityType?) -> Any? { nil }

    @discardableResult
    public func activityViewController(_ value0: UIActivityViewController, subjectForActivityType value1: UIActivity.ActivityType?) -> String { "" }

    @discardableResult
    public func activityViewController(_ value0: UIActivityViewController, dataTypeIdentifierForActivityType value1: UIActivity.ActivityType?) -> String { "" }

    @discardableResult
    public func activityViewController(_ value0: UIActivityViewController, thumbnailImageForActivityType value1: UIActivity.ActivityType?, suggestedSize value2: CGSize) -> UIImage? { nil }
}

extension UIActivityItemSource {
    @discardableResult
    public func activityViewControllerPlaceholderItem(_ value0: UIActivityViewController) -> Any { fatalError("preview SDK mock has no inert value for Any") }

    @discardableResult
    public func activityViewController(_ value0: UIActivityViewController, itemForActivityType value1: UIActivity.ActivityType?) -> Any? { nil }

    @discardableResult
    public func activityViewController(_ value0: UIActivityViewController, subjectForActivityType value1: UIActivity.ActivityType?) -> String { "" }

    @discardableResult
    public func activityViewController(_ value0: UIActivityViewController, dataTypeIdentifierForActivityType value1: UIActivity.ActivityType?) -> String { "" }

    @discardableResult
    public func activityViewController(_ value0: UIActivityViewController, thumbnailImageForActivityType value1: UIActivity.ActivityType?, suggestedSize value2: CGSize) -> UIImage? { nil }
}


// mobai-ir-declaration: UIViewControllerTransitionCoordinator
public protocol UIViewControllerTransitionCoordinator {

}

private final class _MobAIUIViewControllerTransitionCoordinator: UIViewControllerTransitionCoordinator {
    init() {}
}

// mobai-ir-declaration: UIViewControllerTransitionCoordinatorContext
public protocol UIViewControllerTransitionCoordinatorContext {

}

private final class _MobAIUIViewControllerTransitionCoordinatorContext: UIViewControllerTransitionCoordinatorContext {
    init() {}
}


/// Thrown by everything below.
///
/// A stand-in has no behaviour to offer, and throwing is the only
/// way to satisfy a return type without inventing a value. At a
/// `try?` call site this becomes nil, so the screen renders empty
/// rather than wrong, and nothing crashes.
public enum MockUnavailable: Error { case notImplemented }
